version: 2
jobs:
  build-job:
    machine: true
    # docker:
    #   - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Docker build
          command: ./bin/build.sh
  deploy-job:
    machine: true
    # docker:
    #   - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Publish to GH Pages
          command: ./bin/publish.sh

workflows: 
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
